version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: common_university_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: university
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/university
      SPRING_DATASOURCE_USERNAME: university_user
      SPRING_DATASOURCE_PASSWORD: password

networks:
  app-network:
    driver: bridge
