spring:
  mvc:
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        enabled: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://dpg-d0ur2nmuk2gs739bpbmg-a.frankfurt-postgres.render.com:5432/university_qqi8
    username: university_qqi8_user
    password: h8kffDTXLuM9ZoUk4qKoejRIvACoF1c6
    driver-class-name: org.postgresql.Driver
  application:
    name: Bootstrap Spring Boot
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    database-platform:
      - profile: "postgres"
        value: "org.hibernate.dialect.PostgreSQLDialect"
      - profile: "default"
        value: "org.hibernate.dialect.H2Dialect"
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    org:
      springframework:
        web: TRACE
        springframework: TRACE
    com:
      foxminded: TRACE
app:
  pagination:
    default-page: 0
    default-size: 10
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:ssl/foxminded_university.pfx
    key-store-password: 1111