version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: university-postgres
    environment:
      POSTGRES_USER: common_university_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: university
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: university-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d0ur2nmuk2gs739bpbmg-a.frankfurt-postgres.render.com:5432/university_qqi8
      SPRING_DATASOURCE_USERNAME: university_qqi8_user
      SPRING_DATASOURCE_PASSWORD: h8kffDTXLuM9ZoUk4qKoejRIvACoF1c6
    ports:
      - "8080:8080"
    depends_on:
      - postgres
