spring:
  mvc:
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/university
    username: university_user
    password: password
    driver-class-name: org.postgresql.Driver
  application:
    name: Bootstrap Spring Boot
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    database-platform:
      - profile: "postgres"
        value: "org.hibernate.dialect.PostgreSQLDialect"
      - profile: "default"
        value: "org.hibernate.dialect.H2Dialect"
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
app:
  pagination:
    default-page: 0
    default-size: 10